# Generated by Django 5.0 on 2023-12-31 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logger_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_logger_app.event')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
