# Generated by Django 5.0 on 2023-12-31 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_logger_app', '0002_evententry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='name',
        ),
    ]
